const {test,expect}=require('@playwright/test');
const path=require('node:path');
for(const width of [390,1440]) for(const lang of ['pt','en','es','fr','he']) {
 test(`visual discovery ${lang} ${width}px`,async({page},info)=>{
  const evidence=name=>process.env.VISUAL_EVIDENCE_DIR ? path.resolve(process.env.VISUAL_EVIDENCE_DIR,name) : info.outputPath(name);
  await page.setViewportSize({width,height:900});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.waitForFunction(()=>typeof touristSpots!=='undefined' && document.querySelectorAll('#spots-grid > article').length===touristSpots.length);
  await page.locator('#lang-btn').click();
  await page.locator(`#language-menu button[onclick="setLanguage('${lang}')"]`).click();
  await expect(page.locator('html')).toHaveAttribute('lang',lang);
  await expect(page.locator('html')).toHaveAttribute('dir',lang==='he'?'rtl':'ltr');
  await expect(page.locator('#map')).toBeVisible();
  await expect(page.locator('#tab-map')).toHaveClass(/active/);
  const total=await page.evaluate(()=>touristSpots.length);
  await expect(page.locator('#spots-grid > article')).toHaveCount(total);
  const mismatches=await page.evaluate(()=>{
   const failures=[];
   for(const el of document.querySelectorAll('[data-i18n]')) if(el.textContent!==t(el.dataset.i18n)) failures.push(el.dataset.i18n);
   for(const attr of ['placeholder','aria-label','alt']) for(const el of document.querySelectorAll(`[data-i18n-${attr}]`)) if(el.getAttribute(attr)!==t(el.getAttribute(`data-i18n-${attr}`))) failures.push(attr);
   const cards=[...document.querySelectorAll('#spots-grid > article')];
   cards.forEach((el,i)=>{const tr=getSpotTranslation(touristSpots[i]);if(el.querySelector('h3').textContent!==tr.title || el.querySelector('p').textContent!==(tr.subtitle||tr.description||''))failures.push(touristSpots[i].id)});
   return failures;
  });
  expect(mismatches).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.screenshot({path:evidence(`after-${lang}-${width}.png`)});
  await page.locator('#search-input').fill('Jabaquara');
  await expect(page.locator('#spots-grid > article')).toHaveCount(1);
  await expect(page.locator('#results-count-num')).toHaveText('1');
  expect(await page.evaluate(()=>mapMarkers.length)).toBe(1);
  expect(await page.evaluate(()=>getFilteredSpots().map(s=>s.id))).toEqual(['praia-do-jabaquara']);
  await page.locator('#clear-search-btn').click();
  const cat=page.locator('.cat-pill[data-cat="cachoeiras"]');
  await cat.scrollIntoViewIfNeeded();await cat.click();
  const expected=await page.evaluate(()=>touristSpots.filter(s=>s.category==='cachoeiras').length);
  await expect(page.locator('#spots-grid > article')).toHaveCount(expected);
  await expect(cat).toHaveAttribute('aria-pressed','true');
  expect(await page.evaluate(()=>mapMarkers.length)).toBe(expected);
  await page.locator('#tab-grid').click();
  await expect(page.locator('#tab-grid')).toHaveClass(/active/);
  const details=page.locator('#spots-grid .attraction-card-details').first();
  await details.focus();await page.keyboard.press('Enter');
  await expect(page.locator('#spot-modal')).toBeVisible();
  await expect(page.locator('#spot-modal-title')).toHaveText(await page.evaluate(()=>getSpotTranslation(getFilteredSpots()[0]).title));
  await page.evaluate(()=>closeSpotModal());
  await page.locator('#tab-map').click();
  await expect(page.locator('#tab-map')).toHaveClass(/active/);
  await expect(page.locator('#map')).toBeVisible();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('lang',lang);
  await expect(page.locator('#spots-grid > article')).toHaveCount(total);
  await page.locator('#tab-grid').click();
  await page.locator('#spots-grid > article').first().scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>[...document.querySelectorAll('#spots-grid > article img')].slice(0,4).every(img=>img.complete && img.naturalWidth>0));
  await page.evaluate(()=>{const y=document.querySelector('#spots-grid').getBoundingClientRect().top+scrollY;const bar=document.querySelector('.home-discovery');scrollTo(0,y-64-(innerWidth>=768?bar.offsetHeight:0)-12)});
  await page.screenshot({path:evidence(`cards-${lang}-${width}.png`)});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect(errors).toEqual([]);
 });
}
